Config:
    mensaje-bienvenida: true
    mensaje-bienvenida-texto: "&6Bienvenido al &lHimalaya %player%"
    Spawn:
        x: 0
        y: 0
        z: 0
        yaw: 0
        pitch: 0
        world: world
        status: false